version: "2"

run:
  timeout: 1m
  tests: false
  concurrency: 4

linters:
  default: standard

  settings:
    errcheck:
      check-type-assertions: true

formatters:
  enable:
    - gofmt
    - golines
    - goimports
