export enum Period {
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  THREE_MONTH = '3_MONTH',
  SIX_MONTH = '6_MONTH',
  YEAR = 'YEAR',
  TWO_YEARS = '2_YEARS',
  THREE_YEARS = '3_YEARS',
  FOUR_YEARS = '4_YEARS',
  FIVE_YEARS = '5_YEARS',
  FOREVER = 'FOREVER',
}
